### ISSUE TITLE
download of GLM3r does not work

### ISSUE THREAD

**Issue by rotiferFromItaly** [GLEON/GLM3r#6]
Hi there,
I encountered the same error message as with GLM when trying to download GLM3r.

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

doing:
install.packages("devtools")
devtools::install_github("GLEON/GLM3r")

getting:
testing if installed package can be loaded from temporary location
Error in slibs[are_shared] : invalid subscript type 'list'
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/GLM3r’
Error: Failed to install 'GLM3r' from GitHub:
  (converted from warning) installation of package ‘/var/folders/jz/41p1rmwj7gj7g_lpwwsm5vy40000gn/T//RtmpuvfKdJ/file78f72de45669/GLM3r_3.1.16.tar.gz’ had non-zero exit status

any help is appreciated,
best regards from Italy

**Comment by hdugan** [comment]
We have been installing GLM3r on a lot of different platforms this week, and have not run into this issue. It seems like it might be a staged installation issue (again have not encountered this before). See: https://developer.r-project.org/Blog/public/2019/02/14/staged-install/

If you can, please fork this repository to your own profile, and try adding 
`StagedInstall: no` to the DESCRIPTION file. Let us know if this solves the problem. 
Thanks!

**Comment by rotiferFromItaly** [comment]
I have no idea what "If you can, please fork this repository to your own profile, and try adding
StagedInstall: no to the DESCRIPTION file. " means and therefore I am still unable to install GLM3r
C'est La Vie

**Comment by rotiferFromItaly** [comment]
The solution to this interesting problem is:
upgrade R to 3.6.1
and the installation process works :o))
