### ISSUE TITLE
Add start-up message for the disclaimer and copyright notice. 

### ISSUE THREAD

**Issue by jordansread** [GLEON/GLM3r#7]
#### By downloading the software you agree to the following terms:

>>>
The University of Western Australia has developed the code with reasonable care and skill, however, the authors do not make or imply any warranty as to the quality of simulated output from the software supplied. Nor do the authors accept any responsibility for the use of the model including any advice or information which the user may give, or opinions which they express, arising from model simulated output

**Comment by hdugan** [comment]
Added to package startup 👍
